image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
    visibility: private

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: cp apps/app/src/.env.example apps/app/.env && npm i # runs during prebuild
    command: npm run dev

vscode:
  extensions:
  - pflannery.vscode-versionlens
  - vymarkov.nodejs-devops-extension-pack
  - tabnine.tabnine-vscode
  - https://github.com/nrwl/nx-console/releases/download/v17.2.0/nx-console.vsix
