image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
    visibility: private

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      nvm install
      nvm use
      cp apps/app/src/.env.example apps/app/.env
      npm install

      npm --version
      node --version
      npx firebase --version
    before: npm install
  - command: npx firebase --token=$FIREBASE_TOKEN projects:list
  - command: npx nx run spotify-auth-firebase-functions:serve

vscode:
  extensions:
  - pflannery.vscode-versionlens
  - vymarkov.nodejs-devops-extension-pack
  - tabnine.tabnine-vscode
  - amazonwebservices.aws-toolkit-vscode
  - firsttris.vscode-jest-runner
  - nrwl.angular-console
