version: "3.6"

services:
  redis:
    image: redis:5
    ports:
    - 6379/tcp
    restart: on-failure:5

  superhero-api:
    build:
      context: .
      dockerfile: apps/superhero-api/Dockerfile
      args:
        app_name: superhero-api

  app:
    restart: on-failure:5
    build:
      context: .
      dockerfile: apps/app/Dockerfile
    environment:
      NODE_ENV: ${APP_ENV:-development}
      FOO: bar
    working_dir: /usr/src/app/dist/apps/superhero-api
    ports:
      - 3000:3000/tcp
