version: "3.6"

services:
  redis:
    image: redis:5
    ports:
    - 6379/tcp
    restart: on-failure:5

  app:
    build:
      context: .
      dockerfile: apps/app/Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    restart: on-failure:5
    environment:
      NODE_ENV: ${APP_ENV:-development}
      FOO: bar
    ports:
      - 3000:3000/tcp
