@baseUrl={{$dotenv BASE_URL }}
@token={{$dotenv token}}

GET {{baseUrl}}/spotifyAuth

### Remove track from own playlist
### https://open.spotify.com/playlist/0mHp4YGQafLceibtfhe1FB

GET {{baseUrl}}/cloneOrEditPlaylistHttp?playlist_id=0mHp4YGQafLceibtfhe1FB
Authorization: Bearer {{token}}

### Clone the original playlist due to lack of permissions to edit playlist tracks

# https://open.spotify.com/playlist/37i9dQZF1DX5ECfKO3L7Vd
GET {{baseUrl}}/cloneOrEditPlaylistHttp?playlist_id=37i9dQZF1DX5ECfKO3L7Vd
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/convertCustomTokenToIdToken
Authorization: Bearer {{$dotenv customUserToken}}
