name: Build
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Install Dependencies'
        run: npm ci
        
      - uses: mansagroup/nrwl-nx-action@v2
        name: 'Build apps'
        with:
          targets: build
          affected: 'true' # Defaults to true, therefore optional

      - uses: mansagroup/nrwl-nx-action@v2
        name: 'Build docker images'     
        with:
          targets: build
