name: Build
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    # if: ${{ github.ref == 'refs/heads/feat-deploy-by-aws-copilot' }}
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Install Dependencies'
        run: npm ci

      - name: Build apps
        run: npm run nx affected:build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Setup AWS Copilot
        uses: softprops/setup-aws-copilot@v1
        with:
          version: v1.6.0

      - name: Deploy affected apps
        env:
          NODE_ENV: dev
        run: npx nx affected --target=deploy --all

      # - name: 'Build docker images'
      #   run: npm run nx affected -- --target=docker --push --all
